P900Ferries - Copy/FerryWebApp/Controllers/BookingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLayer;
using Microsoft.AspNet.Identity;
//using Microsoft.AspNetCore.Mvc;
using Microsoft.Owin.BuilderProperties;
using Models.Models.BookingModels;

namespace FerryWebApp.Controllers
{
    [Authorize(Roles = "Customer")]
    public class BookingController : Controller
    {
        public BookingService _Booking = new BookingService();
        // GET: Booking
        public ActionResult JourneyPicker()
        {
            var journey = new ChooseJourneyModel(); 
            journey.LocationList = _Booking.GetLocationList();  
            return View("JourneyPicker", journey);
        }
        public ActionResult StoreJourney(ChooseJourneyModel journey)
        {
            journey.LocationFrom = _Booking.GetLocationById(journey.LocationFrom.LocationId);
            journey.LocationTo = _Booking.GetLocationById(journey.LocationTo.LocationId);
            Session["journey"] = journey;
            return RedirectToAction("ListJourneys", journey);
        }
        public ActionResult ListJourneys(ChooseJourneyModel journey)
        {
            journey = (ChooseJourneyModel)Session["journey"];
            journey.JourneyGrid = _Booking.ListJourneysMain(journey);
            return View("ListJourneys", journey);
        }
        public ActionResult StoreJourneyInfo(int journeyId)
        {
            var journey = (ChooseJourneyModel)Session["journey"];
            var journeyInfo = _Booking.GetJourneyById(journey, journeyId);
            Session["journeyInfo"] = journeyInfo;
            return RedirectToAction("SelectCarsPassengers", new { id = journeyInfo.JourneyId });
        }

        //[Route("Booking/SelectCarsPassengers/{id:int}")]
        [HttpGet]
        public ActionResult SelectCarsPassengers(int id)
        {
            var schedule = _Booking.GetScheduleById(id);
            var carsPassengers = new CarsPassengers();
            carsPassengers.CostPerVehicle = schedule.CostPerVehicle;
            carsPassengers.CostPerPerson = schedule.CostPerPerson;

            return View("SelectCarsPassengers", carsPassengers);
        }
        [HttpPost]
        public ActionResult StoreCarsPassengers(CarsPassengers carsPassengers)
        {
            if (ModelState.IsValid)
            {
                carsPassengers.TotalCost = (carsPassengers.CostPerVehicle * carsPassengers.NumberOfCars)
                + (carsPassengers.CostPerPerson * carsPassengers.NumberOfPassengers);
                Session["carsPassengers"] = carsPassengers;
                return RedirectToAction("BookingAddress");
            }
            return null;
        }
        public ActionResult BookingAddress()
        {
            return View();
        }
        [HttpPost]
        public ActionResult StoreContactDetails(ContactDetails address)
        {
            if (ModelState.IsValid)
            {
                Session["address"] = address;
                return RedirectToAction("BookingSummary");
            }
            else
            {
                return View("BookingAddress", address);
            }
        }
        public ActionResult BookingSummary()
        {
            var addressData = (ContactDetails)Session["address"];
            var journeyData = (ChooseJourneyModel)Session["journey"];
            var journeyInfoData = (JourneyInfo)Session["journeyInfo"];
            var carsPassengersData = (CarsPassengers)Session["carsPassengers"];
            var bookingSummary = new BookingSummary
            {
                PersonName = addressData.Name,
                Line1 = addressData.Line1,
                Line2 = addressData.Line2,
                City = addressData.City,
                Postcode = addressData.Postcode,
                DepartureLocation = journeyData.LocationFrom.Name,
                DepartTime = journeyInfoData.DepartureTime,
                ArrivalLocation = journeyData.LocationTo.Name,
                ArrivalTime = journeyInfoData.ArrivalTime,
                ArrivalDate = journeyInfoData.ArrivalDate,
                DateFrom = journeyData.DateFrom,
                NumberOfCars = carsPassengersData.NumberOfCars,
                NumberOfPassengers = carsPassengersData.NumberOfPassengers,
                TotalCost = carsPassengersData.TotalCost
            };
            Session["bookingSummary"] = bookingSummary;
            return View(bookingSummary);
        }
        public ActionResult BookingConfirmed()
        {
            var addressData = (ContactDetails)Session["address"];
            var journeyData = (ChooseJourneyModel)Session["journey"];
            var journeyInfoData = (JourneyInfo)Session["journeyInfo"];
            var carsPassengersData = (CarsPassengers)Session["carsPassengers"];
            var bookingSummary = (BookingSummary)Session["bookingSummary"];
            
            var chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
            var stringChars = new char[5];
            var random = new Random();

            for (int i = 0; i < stringChars.Length; i++)
            {
                stringChars[i] = chars[random.Next(chars.Length)];
            }

            var bookingRef = new String(stringChars);

            var booking = new BookingConfirmed()
            {
                UserId = User.Identity.GetUserId(),
                BookingReference = bookingRef,
                ArrivalDate = journeyInfoData.ArrivalDate,
                ArrivalLocation = journeyData.LocationTo.Name,
                Cars = carsPassengersData.NumberOfCars,
                Passengers = carsPassengersData.NumberOfPassengers,
                Cost = carsPassengersData.TotalCost,
                CompanyName= journeyInfoData.CompanyName,
                FerryName = journeyInfoData.FerryName,
                DepartureDate = journeyData.DateFrom,
                DepartureLocation = journeyData.LocationFrom.Name,
            };
            return View(booking);
        }
        public ActionResult SaveBooking(BookingConfirmed booking)
        {
            _Booking.AddBooking(booking);
            return RedirectToAction("AddBookingContact", booking);
        }
        public ActionResult AddBookingContact(BookingConfirmed booking)
        {
            var bookingContact = (ContactDetails)Session["address"];
            bookingContact.BookingId = booking.BookingId;
            _Booking.AddBookingContact(bookingContact);
            return RedirectToAction("JourneyPicker");
        }
    }
}

P900Ferries - Copy/FerryWebApp/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Mvc;
using BusinessLayer;
using DataAccess;
using Models.Models;
using Models.Models.CompanyModels;
using Models.Models.FerryModels;

namespace FerryWebApp.Controllers
{
    [Authorize(Roles = "Employee")]
    public class CompanyController : Controller
    {
        public CompanyService _Company = new CompanyService();
        public FerriesService _Ferry = new FerriesService();

        [HttpPost]
        public ActionResult SaveEditCompany(CompanyViewModel company)
        {
            _Company.UpdateCompany(company);
            return RedirectToAction("Delete", new {id = company.CompanyId});
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var company = _Company.GetCompanyById(id);
            return View("Edit", company);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PopulateGrid(CompanyViewModel company)
        {

            company.CompanyGrid = _Company.ListSearch(company.Name);
            return View("List", company);
        }

        [HttpGet]
        [Route("Company/Delete/{id:int}")]
        public ActionResult Delete(int id)
        {
            var company = _Company.GetCompanyById(id);
            company.FerryGrid = _Company.ListFerriesByCompanyId(id);
            return View("Delete", company);
        }
        [HttpPost]
        public ActionResult DeleteCompany(CompanyViewModel company)
        {
            if (company.FerryGrid== null)
            {
                _Company.DeleteCompany(company.CompanyId);
            }
            return RedirectToAction("List");

        }
        public ActionResult List(CompanyViewModel company)
        {
            if (company == null)
            {
                return View("List", new CompanyViewModel());
            }
            else
            {

                return View("List", company);
            }
        }
        public ActionResult Create()
        {
            return View("Create");
        }
        public ActionResult AddCompany(CompanyViewModel company) 
        {
            if (ModelState.IsValid)
            {
                _Company.AddCompany(company);
                return RedirectToAction("Delete", new {id = company.CompanyId});
            }
            else
            {
                return View("Create", company);
            }    
        }
        public ActionResult Edit()
        {
            return View("Edit");
        }
        public ActionResult OpenEditPage()
        {
            return View("Edit");
        }
        public ActionResult OpenAddPage()
        {
            return View("Create");
        }
        public ActionResult Delete()
        {
            return View("Delete");
        }
        public ActionResult Cancel()
        {
            return View("Create");
        }
    }
}

P900Ferries - Copy/FerryWebApp/Views/Shared/_BookingLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - IshyFerries</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.1/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/mvc/5.2.3/jquery.validate.unobtrusive.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-dark navbar-expand-md bg-dark justify-content-center">
        <a href="@Url.Action("JourneyPicker", "Booking")" class="navbar-brand d-flex w-50 mr-auto">IshyFerries</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsingNavbar3">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse w-100" id="collapsingNavbar3">
            <ul class="navbar-nav w-100 justify-content-center">
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("JourneyPicker", "Booking")">Pick a Journey</a>
                </li>
            </ul>
            <ul class="nav navbar-nav ml-auto w-100 justify-content-end">
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Login", "Login")">Sign Out</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - IshyFerries Booking System</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

P900Ferries - Copy/FerryWebApp/Views/Shared/_EmployeeLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - IshyFerries</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.1/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/mvc/5.2.3/jquery.validate.unobtrusive.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-dark navbar-expand-md bg-dark justify-content-center">
        <a href="@Url.Action("Home", "Home")" class="navbar-brand d-flex w-50 mr-auto">IshyFerries</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsingNavbar3">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse w-100" id="collapsingNavbar3">
            <ul class="navbar-nav w-100 justify-content-center">
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("List", "Ferry")">Ferries</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("List", "Company")">Companies</a>
                </li>
            </ul>
            <ul class="nav navbar-nav ml-auto w-100 justify-content-end">
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Login", "Login")">Sign Out</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - IshyFerries Booking System</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>