Car Share/CarShare/CarShareApp/Controllers/DriverController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using BusinessLogic.DriverLogic;
using BusinessLogic;
using Microsoft.AspNet.Identity;
using PresentationModels.Driver;
using PresentationModels.Login;
using BusinessLogic.GeneralLogic;
using System.Management.Instrumentation;
using PresentationModels.Passenger;
using System.Data.Entity.Core.Common.CommandTrees;

namespace CarShareApp.Controllers
{
    /// <summary>
    /// Manages all the pages for driver journeys, stops and approved passengers
    /// </summary>
    [Authorize]
    public class DriverController : BaseController
    {
        private DriverStopService _DriverStop = new DriverStopService();
        private LocationService _Location = new LocationService();
        private DriverJourneyService _DriverJourney = new DriverJourneyService();

        /// <summary>
        /// initialises all the required object for the manage journeys page
        /// </summary>
        /// <returns></returns>
        public ManageJourneys InitialiseManageJourneys()
        {
            var manageJourney = new ManageJourneys();
            manageJourney.JourneyGrid = _DriverJourney.List(ApplicationUser.UserId);
            foreach (var item in manageJourney.JourneyGrid)
            {
                var passengers = _DriverJourney.ListApprovedPassengersForJourney(item.DriverJourneyId);
                item.Passengers = new List<PresUser>();
                foreach (var passenger in passengers)
                {
                    item.Passengers.Add(passenger);
                }
                if (item.SeatsAvailable == 0)
                {
                    _DriverJourney.LockJourney(item.DriverJourneyId);
                }
            }
            return manageJourney;
        }

        /// <summary>
        /// returns a view with a grid of all the journeys
        /// </summary>
        /// <returns></returns>
        public ActionResult ManageJourneys()
        {
            
            return View(InitialiseManageJourneys());
        }

        /// <summary>
        /// Locks a driver's journey so no one can book onto it
        /// </summary>
        /// <param name="driverJourneyId"></param>
        /// <returns></returns>
        public ActionResult LockJourney(int driverJourneyId)
        {
            _DriverJourney.LockJourney(driverJourneyId);

            return View("ManageJourneys", InitialiseManageJourneys());
        }

        /// <summary>
        /// Unlocks a journey so users can book onto it 
        /// </summary>
        /// <param name="driverJourneyId"></param>
        /// <returns></returns>
        public ActionResult UnlockJourney(int driverJourneyId)
        {
            _DriverJourney.UnlockJourney(driverJourneyId);
            return View("ManageJourneys", InitialiseManageJourneys());
        }

        /// <summary>
        /// Returns view where a new journey can be made for a driver 
        /// </summary>
        /// <returns></returns>
        public ActionResult AddJourney()
        {
            var journey = new AddJourney();
            journey.StopsGrid = _DriverJourney.ListStops(ApplicationUser.UserId);
            return View(journey);
        }

        /// <summary>
        /// creates a new journey for driver 
        /// </summary>
        /// <param name="journey"></param>
        /// <returns></returns>
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult CreateJourney(AddJourney journey)
        {
            journey.DriverId = ApplicationUser.UserId;
            journey.StopsGrid = _DriverJourney.ListStops(ApplicationUser.UserId);
            if (!ModelState.IsValid)
            {
                return View("AddJourney", journey);
            }
            else
            {
                journey.StopsGrid = _DriverJourney.ListStops(ApplicationUser.UserId);
                _DriverJourney.Create(journey);
                ViewBag.SuccessMessage = "Journey successfully created";
                ModelState.Clear();
                var addJourney = new AddJourney();
                addJourney.StopsGrid = _DriverJourney.ListStops(ApplicationUser.UserId);
                return View("AddJourney", addJourney);
            }
        }

        /// <summary>
        /// Returns view with a grid of all the approved passengers for a driver
        /// </summary>
        /// <returns></returns>
        public ActionResult ApprovedPassengers(ApprovedPassengers approvedPassenger)
        {
            approvedPassenger.ApprovedList = _DriverJourney.ListApprovedPassengers(ApplicationUser.UserId);
            approvedPassenger.Passengers = _User.List(ApplicationUser.UserId);
            return View(approvedPassenger);
        }

        /// <summary>
        /// Adds an approved passenger to a user's approved passengers list
        /// </summary>
        /// <param name="approved"></param>
        /// <returns></returns>
        public ActionResult AddApprovedPassenger(ApprovedPassengers approved)
        {
            if (ModelState.IsValid)
            {
                _DriverJourney.ApprovePassenger(ApplicationUser.UserId, approved.PassengerId);
                approved.Passengers = _User.List(ApplicationUser.UserId);
                approved.ApprovedList = _DriverJourney.ListApprovedPassengers(ApplicationUser.UserId);
                return View("ApprovedPassengers", approved);
            }
            else
            {
                approved.Passengers = _User.List(ApplicationUser.UserId);
                approved.ApprovedList = _DriverJourney.ListApprovedPassengers(ApplicationUser.UserId);
                return View("ApprovedPassengers", approved);
            }
        }

        /// <summary>
        /// Removes a passenger from a user's approved list
        /// </summary>
        /// <param name="passengerId"></param>
        /// <returns></returns>
        public ActionResult RemovePassenger(int passengerId)
        {
            _DriverJourney.RemovePassenger(ApplicationUser.UserId, passengerId);
            var approved = new ApprovedPassengers();
            approved.Passengers = _User.List(ApplicationUser.UserId);
            approved.ApprovedList = _DriverJourney.ListApprovedPassengers(ApplicationUser.UserId);
            return View("ApprovedPassengers", approved);
        }

        /// <summary>
        /// Returns a view with all the stops that a driver is willing to make on the
        /// way to work
        /// </summary>
        /// <returns></returns>
        public ActionResult Stops()
        {
            var stop = new Stops();
            stop.StopsGrid = _DriverStop.List(ApplicationUser.UserId);
            stop.LocationList = _Location.List();
            return View(stop);
        }

        /// <summary>
        /// Deletes a stop from the driver's stops list
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult DeleteStop(int id)
        {
            _DriverStop.Delete(ApplicationUser.UserId, id);
            return RedirectToAction("Stops");
        }

        /// <summary>
        /// Opens a partial view with a modal allowing user to add a new stop
        /// </summary>
        /// <param name="stop"></param>
        /// <returns></returns>
        public ActionResult AddStop(Stops stop)
        {
            return PartialView("AddStop", stop);
        }

        /// <summary>
        /// Inserts the new stop in database
        /// </summary>
        /// <param name="stop"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult CreateStop(Stops stop)
        {
            
            if (ModelState.IsValid)
            {
                stop.DriverId = ApplicationUser.UserId;
                var message = _DriverStop.Create(stop);
                ViewBag.Message = message;
                var newStop = new Stops();
                newStop.StopsGrid = _DriverStop.List(ApplicationUser.UserId);
                newStop.LocationList = _Location.List();
                return View("Stops", newStop);
            }
            else
            {
                var newStop = new Stops();
                newStop.StopsGrid = _DriverStop.List(ApplicationUser.UserId);
                newStop.LocationList = _Location.List();
                return View("Stops", newStop);
            }
        }
    }
}

Car Share/CarShare/CarShareApp/Controllers/PassengerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLogic;
using BusinessLogic.DriverLogic;
using BusinessLogic.GeneralLogic;
using BusinessLogic.PassengerLogic;
using Microsoft.AspNet.Identity;
using PresentationModels.Driver;
using PresentationModels.Login;
using PresentationModels.Passenger;

namespace CarShareApp.Controllers
{
    /// <summary>
    /// Manages pages and actions for passenger bookings
    /// </summary>
    [Authorize]
    public class PassengerController : BaseController
    {
        private DriverStopService _DriverStop = new DriverStopService();
        private DriverJourneyService _DriverJourney = new DriverJourneyService();
        private PassengerService _Passenger = new PassengerService();
        private LocationService _Location = new LocationService();

        /// <summary>
        /// Initialises the components to open the passenger manage journey page
        /// </summary>
        /// <returns></returns>
        public ManagePassengerJourney InitialiseManageJourneys()
        {
            var manageJourney = new ManagePassengerJourney();
            manageJourney.JourneyGrid = _Passenger.ListJourneys();
            foreach (var model in manageJourney.JourneyGrid)
            {
                model.PickUpTime = ConvertFromIntToTime(model.JourneyStop.TimeFromHome) + model.JourneyStop.DriverJourney.LeavingTime;
            }
            return manageJourney;
        }

        /// <summary>
        /// Returns view with grid of all upcoming journeys booked by the user as
        /// a passenger
        /// </summary>
        /// <returns></returns>
        public ActionResult ManageJourneys()
        {
            
            return View(InitialiseManageJourneys());
        }

        /// <summary>
        /// If a user has been rejected or his/her request is still pending then deletes the passengerjourney 
        /// </summary>
        /// <param name="passengerJourneyId"></param>
        /// <returns></returns>
        public ActionResult CancelPassengerJourney(int passengerJourneyId)
        {
            var passengerJourney = _Passenger.GetJourney(passengerJourneyId);
            if (passengerJourney.Status.StatusId == 3 || passengerJourney.Status.StatusId == 2)
            {
                _Passenger.DeleteJourney(passengerJourneyId);
            }
            return View("ManageJourneys", InitialiseManageJourneys());
        }

        /// <summary>
        /// Allows user to search for available drivers depending on the inputted criteria
        /// </summary>
        /// <returns></returns>
        public ActionResult BookJourney(BookJourney journey)
        {
            if (journey.Location == null)
            {
                journey.AvailableJourneysGrid = null;
                journey.LocationList = _Location.List();
                return View(journey);
            }
            else
            {
                journey.AvailableJourneysGrid = _Passenger.FindJourneys(journey, ApplicationUser.UserId);
                journey.LocationList = _Location.List();
                return View(journey);
            }
        }

        /// <summary>
        /// Searches for all drivers matching search criteria and displays them in a grid
        /// </summary>
        /// <param name="journey"></param>
        /// <returns></returns>
        public ActionResult FindJourneys(BookJourney journey)
        {
            if (ModelState.IsValid)
            {
                journey.AvailableJourneysGrid = _Passenger.FindJourneys(journey, ApplicationUser.UserId);
                if (journey.AvailableJourneysGrid.Count == 0)
                {
                    ViewBag.Message = "No journeys matching your criteria found";
                }
                foreach (var item in journey.AvailableJourneysGrid)
                {
                    var stop = _Passenger.GetStop(item.DriverJourney.DriverJourneyId, journey.Location.LocationId);
                    item.JourneyStop = stop;
                    item.PickUpTime = ConvertFromIntToTime(stop.TimeFromHome) + item.DriverJourney.LeavingTime;
                    var stopList = _Passenger.ListStops(item.DriverJourney.DriverJourneyId);
                    for (int i = 0; i < stopList.Count; i++)
                    {
                        item.ArrivalTime = ConvertFromIntToTime(stopList[i].TimeFromHome + stopList[i].Location.DistanceToWork) + item.DriverJourney.LeavingTime;
                    }
                }
                journey.LocationList = _Location.List();
                return View("BookJourney", journey);
            }
            else
            {
                journey.LocationList = _Location.List();
                return View("BookJourney", journey);
            }
        }

        /// <summary>
        /// converts from an integer into a timespan type, so the arrival and pickup times
        /// can be calculated
        /// </summary>
        /// <param name="mins"></param>
        /// <returns></returns>
        public TimeSpan ConvertFromIntToTime(int mins)
        {
            var time = new TimeSpan(00, mins, 00);
            return time;
        }

        /// <summary>
        /// Creates a new passenger journey after a user books it
        /// </summary>
        /// <param name="journeyId"></param>
        /// <param name="locationId"></param>
        /// <returns></returns>
        public ActionResult CreatePassengerJourney(int journeyId, int locationId)
        {
            var journeyStop = _Passenger.GetStop(journeyId, locationId);
            var passenger = new PresUser
            {
                UserId = ApplicationUser.UserId,
                Name = ApplicationUser.Name
            };

            var message = _Passenger.CreateJourney(passenger, journeyStop.DriverJourney.DriverJourneyId,journeyStop.DriverJourney.DriverId, journeyStop.JourneyStopId, 3);
            if (message == "Journey has been successfully booked")
            {
                ViewBag.SuccessMessage = message;
            }
            else if (message == "Failed to book journey. This journey has been locked by the driver")
            {
                ViewBag.FailureMessage = message;
            }
            var journey = new BookJourney();
            journey.LocationList = _Location.List();
            return View("BookJourney", journey);
        }
    }
}

Car Share/CarShare/CarShareApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Ishy's' Incredible Car Share</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.1/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/mvc/5.2.3/jquery.validate.unobtrusive.min.js"></script>
    <!-- Styles -->
    @*<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2-bootstrap-5-theme@1.3.0/dist/select2-bootstrap-5-theme.min.css" />
    <!-- Or for RTL support -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2-bootstrap-5-theme@1.3.0/dist/select2-bootstrap-5-theme.rtl.min.css" />

    <!-- Scripts -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.0/dist/jquery.slim.min.js"></script>
    @*<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>*@
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
</head>
<body class="p-0" style="background-color:#DDC3A5; font-family: sans-serif ">
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #201E20;">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="@Url.Action("Home", "Home")" style="color: #DDC3A5">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#DDC3A5" class="bi bi-house" viewBox="0 0 16 16">
                                <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.707 1.5ZM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5 5 5Z" />
                            </svg>
                            Home
                        </a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color: #DDC3A5">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-car-front-fill" viewBox="0 0 16 16">
                                <path d="M2.52 3.515A2.5 2.5 0 0 1 4.82 2h6.362c1 0 1.904.596 2.298 1.515l.792 1.848c.075.175.21.319.38.404.5.25.855.715.965 1.262l.335 1.679c.033.161.049.325.049.49v.413c0 .814-.39 1.543-1 1.997V13.5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5v-1.338c-1.292.048-2.745.088-4 .088s-2.708-.04-4-.088V13.5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5v-1.892c-.61-.454-1-1.183-1-1.997v-.413a2.5 2.5 0 0 1 .049-.49l.335-1.68c.11-.546.465-1.012.964-1.261a.807.807 0 0 0 .381-.404l.792-1.848ZM3 10a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm10 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2ZM6 8a1 1 0 0 0 0 2h4a1 1 0 1 0 0-2H6ZM2.906 5.189a.51.51 0 0 0 .497.731c.91-.073 3.35-.17 4.597-.17 1.247 0 3.688.097 4.597.17a.51.51 0 0 0 .497-.731l-.956-1.913A.5.5 0 0 0 11.691 3H4.309a.5.5 0 0 0-.447.276L2.906 5.19Z" />
                            </svg>
                            Driver
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown" style="color: #DDC3A5">
                            <li><a class="dropdown-item" href="@Url.Action("ManageJourneys", "Driver")">Manage Journeys</a></li>
                            <li><a class="dropdown-item" href="@Url.Action("AddJourney", "Driver")">Add a Journey</a></li>
                            <li><a class="dropdown-item" href="@Url.Action("ApprovedPassengers", "Driver")">Approved Passengers</a></li>
                            <li><a class="dropdown-item" href="@Url.Action("Stops", "Driver")">Manage Stops</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color: #DDC3A5">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                                <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
                                <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z" />
                            </svg>
                            Passenger
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown" style="color: #DDC3A5">
                            <li><a class="dropdown-item" href="@Url.Action("ManageJourneys", "Passenger")">Manage Journeys</a></li>
                            <li><a class="dropdown-item" href="@Url.Action("BookJourney", "Passenger")">Book a Journey</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="@Url.Action("MileBalance", "MileBalance")" style="color: #DDC3A5">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-currency-exchange" viewBox="0 0 16 16">
                                <path d="M0 5a5.002 5.002 0 0 0 4.027 4.905 6.46 6.46 0 0 1 .544-2.073C3.695 7.536 3.132 6.864 3 5.91h-.5v-.426h.466V5.05c0-.046 0-.093.004-.135H2.5v-.427h.511C3.236 3.24 4.213 2.5 5.681 2.5c.316 0 .59.031.819.085v.733a3.46 3.46 0 0 0-.815-.082c-.919 0-1.538.466-1.734 1.252h1.917v.427h-1.98c-.003.046-.003.097-.003.147v.422h1.983v.427H3.93c.118.602.468 1.03 1.005 1.229a6.5 6.5 0 0 1 4.97-3.113A5.002 5.002 0 0 0 0 5zm16 5.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0zm-7.75 1.322c.069.835.746 1.485 1.964 1.562V14h.54v-.62c1.259-.086 1.996-.74 1.996-1.69 0-.865-.563-1.31-1.57-1.54l-.426-.1V8.374c.54.06.884.347.966.745h.948c-.07-.804-.779-1.433-1.914-1.502V7h-.54v.629c-1.076.103-1.808.732-1.808 1.622 0 .787.544 1.288 1.45 1.493l.358.085v1.78c-.554-.08-.92-.376-1.003-.787H8.25zm1.96-1.895c-.532-.12-.82-.364-.82-.732 0-.41.311-.719.824-.809v1.54h-.005zm.622 1.044c.645.145.943.38.943.796 0 .474-.37.8-1.02.86v-1.674l.077.018z" />
                            </svg>
                            Mile Balance
                        </a>
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="@Url.Action("SignOut", "Login")" style="color: #DDC3A5">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#DDC3A5" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z" />
                                <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z" />
                            </svg>
                            Sign Out (User: @User.Identity.Name)
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
    </div>
</body>
</html>